# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dense_klnmf <- function(V, W, H, vcolsum, vrowsum, method, max_iter, init_em_iter, subprob_iter, batch_size, epoch_length, shift_parameter_input, step_size_input, reportnum, verbose) {
    .Call('_scipi_klnmf_dense_klnmf', PACKAGE = 'scipi.klnmf', V, W, H, vcolsum, vrowsum, method, max_iter, init_em_iter, subprob_iter, batch_size, epoch_length, shift_parameter_input, step_size_input, reportnum, verbose)
}

scipi_dense_klnmf <- function(V, W, H, vcolsum, vrowsum, max_iter, init_em_iter, subprob_iter, shift_parameter_input, step_size_input, verbose) {
    .Call('_scipi_klnmf_scipi_dense_klnmf', PACKAGE = 'scipi.klnmf', V, W, H, vcolsum, vrowsum, max_iter, init_em_iter, subprob_iter, shift_parameter_input, step_size_input, verbose)
}

stochastic_scipi_dense_klnmf <- function(V, W, H, vcolsum, vrowsum, max_iter, init_em_iter, subprob_iter, batch_size, epoch_length, shift_parameter_input, step_size_input, verbose) {
    .Call('_scipi_klnmf_stochastic_scipi_dense_klnmf', PACKAGE = 'scipi.klnmf', V, W, H, vcolsum, vrowsum, max_iter, init_em_iter, subprob_iter, batch_size, epoch_length, shift_parameter_input, step_size_input, verbose)
}

